name: Build commit

on:
  push:
    branches-ignore:
      - "v**"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: read

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
          cache: gradle

      - name: Build with Gradle
        run: ./gradlew assembleRelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Sign APK
        id: sign_apk
        uses: ilharp/sign-android-release@v1
        with:
          releaseDir: ./app/build/outputs/apk/release/
          signingKey: ${{ secrets.KEYSTORE_BASE64 }}
          keyAlias: ${{ secrets.KEYSTORE_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Rename signed APK
        run: mv ${{steps.sign_apk.outputs.signedFile}} ensi-manager.apk

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ensi-manager
          path: ensi-manager.apk